import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ReactScan from "@/components/dev/ReactScan";
import NanoStoreLogger from "@/components/dev/NanoStoreLogger";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/* This is a dev tool 👇 */}
      <ReactScan />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <NanoStoreLogger />
      </body>
    </html>
  );
}
